import { Header } from "@/components/HomePage/Header/Header";
import { Footer } from "@/components/HomePage/Footer/Footer";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const popins = Poppins({ subsets: ["latin"], weight: ["400","500","300","700"], variable: "--font-popins="});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${popins.className} flex flex-col justify-between h-full leading-normal	`}
      >
        <Header />
        <main className="flex-auto ">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
